//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class HW_RED
    {
        public string NUM_SERIE { get; set; }
        public int NUM_PUERTOS { get; set; }
        public int VELOCIDAD { get; set; }
    
        public virtual DISPOSITIVOS DISPOSITIVOS { get; set; }

        public class GetType
        {
        }
    }
}
