//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoMFEEntities : DbContext
    {
        public ProyectoMFEEntities()
            : base("name=ProyectoMFEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<DISPOSITIVOS> DISPOSITIVOS { get; set; }
        public virtual DbSet<HISTORICO_SOLICITUDES> HISTORICO_SOLICITUDES { get; set; }
        public virtual DbSet<HW_RED> HW_RED { get; set; }
        public virtual DbSet<ORDENADORES> ORDENADORES { get; set; }
        public virtual DbSet<PANTALLAS> PANTALLAS { get; set; }
        public virtual DbSet<SOLICITUDES> SOLICITUDES { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    
        public virtual int ACEPTAR_SOLICITUD(string correo, string num_dispositivo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var num_dispositivoParameter = num_dispositivo != null ?
                new ObjectParameter("num_dispositivo", num_dispositivo) :
                new ObjectParameter("num_dispositivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACEPTAR_SOLICITUD", correoParameter, num_dispositivoParameter);
        }
    
        public virtual int FINALIZAR_SOLICITUD(string correo, string num_dispositivo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var num_dispositivoParameter = num_dispositivo != null ?
                new ObjectParameter("num_dispositivo", num_dispositivo) :
                new ObjectParameter("num_dispositivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FINALIZAR_SOLICITUD", correoParameter, num_dispositivoParameter);
        }
    
        public virtual int INSERTAR_SOLICITUD(string correo, string num_dispositivo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var num_dispositivoParameter = num_dispositivo != null ?
                new ObjectParameter("num_dispositivo", num_dispositivo) :
                new ObjectParameter("num_dispositivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_SOLICITUD", correoParameter, num_dispositivoParameter);
        }
    
        public virtual int RECHAZAR_SOLICITUD(string correo, string num_dispositivo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var num_dispositivoParameter = num_dispositivo != null ?
                new ObjectParameter("num_dispositivo", num_dispositivo) :
                new ObjectParameter("num_dispositivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RECHAZAR_SOLICITUD", correoParameter, num_dispositivoParameter);
        }
    }
}
