//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUDES
    {
        public string NUM_SERIE { get; set; }
        public int ID_USUARIO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual DISPOSITIVOS DISPOSITIVOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
